ALTER TABLE themes
  ADD COLUMN code VARCHAR(32) NULL AFTER id;

UPDATE themes
SET code = CASE id
  WHEN 1 THEN 'MATH-05-ELEM-OPS'
  WHEN 2 THEN 'MATH-06-ARITH-OPS'
  WHEN 3 THEN 'GEO-07-ELEM-PLAN'
  WHEN 4 THEN 'ALG-09-EQ-INEQ'
  WHEN 5 THEN 'ALG-08-FRACTIONS'
  WHEN 6 THEN 'ALG-07-EXPRESSIONS'
  WHEN 7 THEN 'GEO-07-CALC'
  WHEN 8 THEN 'ALG-07-EQ'
  WHEN 9 THEN 'GEO-07-PROOFS'
  WHEN 10 THEN 'ALG-08-POWERS-ROOTS'
  WHEN 11 THEN 'ALG-08-QUAD-EQ'
  WHEN 12 THEN 'MATH-07-WORD-PROBLEMS'
  WHEN 13 THEN 'ALG-07-COORD-PLANE'
  WHEN 14 THEN 'ALG-09-FUNCTIONS'
  WHEN 15 THEN 'ALG-11-LOGARITHMS'
  WHEN 16 THEN 'ALG-10-TRIG'
  WHEN 17 THEN 'ALG-11-LIMITS'
  WHEN 18 THEN 'ALG-11-DERIVATIVE'
  WHEN 19 THEN 'ALG-11-INTEGRALS'
  WHEN 20 THEN 'GEO-10-STEREOMETRY'
  WHEN 21 THEN 'ALG-09-COMB-PROG'
  WHEN 22 THEN 'MATH-09-PROBABILITY'
  WHEN 23 THEN 'MATH-09-STATISTICS'
  ELSE CONCAT('T-', id)
END;

ALTER TABLE themes
  MODIFY COLUMN code VARCHAR(32) NOT NULL;

ALTER TABLE themes
  ADD UNIQUE KEY uq_themes_code (code);